name: Upload coverage reports to Codecov
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run:  go mod tidy
      - run:  go build -v ./...
      - run:  make -f Developers.mk coverage
      - name: Run Codecov on GitHub Actions
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

